-- Auto-generated by lp2 transpiler
partial def isqrt (n : Int) : Int :=
  let _ := "Integer square root (floor of sqrt)."; if n < 2 then n else let x := n / 2; let rec loop (x : _) : _ := let x1 := (x + n / x) / 2; if x1 ≥ x then x else loop x1; loop x

partial def fermat_factorization (n : Int) : (Prod Int) Int :=
  let _ := "Factor n using Fermat's factorization method."; if n % 2 == 0 then (Prod.mk 2) (n / 2) else let x := isqrt n; let rec loop (x : _) : _ := let y_sq := x * x - n; let y := isqrt y_sq; if y * y == y_sq then (Prod.mk (x - y)) (x + y) else loop (x + 1); if x * x < n then let x := x + 1; loop x else loop x
